name: docs
on:
  push:
    tags: ["v*"]

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 (Node 24)
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0 (Node 24)
        with:
          python-version: "3.12"
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5 (Node 24)
        with:
          key: mkdocs-material-${{ github.sha }}
          path: ~/.cache
          restore-keys: mkdocs-material-
      - name: Install MkDocs Material
        run: pip install mkdocs-material
      - name: Resolve symlinks for docs
        run: |
          if [ -L docs/changelog.md ]; then
            cp --remove-destination "$(readlink -f docs/changelog.md)" docs/changelog.md
          fi
      - name: Deploy docs
        run: mkdocs gh-deploy --force
